if: type = pull_request

ignore:
  - *.md
  - businesscentral-indexing/*
  - businesscentral-monitoring/*
  - businesscentral/*
  - controller/*
  - kieserver/*
  - quickstarts/library-process/*
  - smartrouter/*
  - example-app-secret-template.yaml
  - rhpam71-image-streams.yaml
  - templates/contrib/jdbc/*
  - templates/docs/*
  
# before_install:
#   - node ./temp.js $TRAVIS_PULL_REQUEST

install:
  - wget https://github.com/jboss-container-images/jboss-kie-modules/raw/master/tools/openshift-template-validator/openshift-template-validator-linux-amd64

script:
  - chmod +x openshift-template-validator-linux-amd64
  - ./openshift-template-validator-linux-amd64 --version
  - ./openshift-template-validator-linux-amd64 validate -d templates/
sudo: false
