
sudo: false
language: generic
stages:
  - compile
    if: type = pull_request
  - wget-validator
  - add-permission
  - verify-validator-version
  - verify-templates
 
jobs:
  include:
    - stage: compile
    - stage: wget-validator
      script: wget https://github.com/jboss-container-images/jboss-kie-modules/raw/master/tools/openshift-template-validator/openshift-template-validator-linux-amd64
    - stage: add-permission
      script: chmod +x openshift-template-validator-linux-amd64
    - stage: verify-validator-version
      script: ./openshift-template-validator-linux-amd64 --version
    - stage: verify-templates
      script: ./openshift-template-validator-linux-amd64 validate -d templates/
