if: type = pull_request

install:
  - wget https://github.com/jboss-container-images/jboss-kie-modules/raw/master/tools/openshift-template-validator/openshift-template-validator-linux-amd64

script:
  - chmod +x openshift-template-validator-linux-amd64
  - ./openshift-template-validator-linux-amd64 --version
  - ./openshift-template-validator-linux-amd64 validadte -d templates/
sudo: false
