install:
  - wget https://github.com/jboss-container-images/jboss-kie-modules/raw/master/tools/openshift-template-validator/openshift-template-validator-linux-amd64

script:
  - openshift-template-validator-linux-amd64 validate -d templates/

sudo: false
